import streamlit as st
import requests
import os
from PIL import Image
import io
import base64
from dotenv import load_dotenv

load_dotenv()

# Configuration
BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")

st.set_page_config(
    page_title="Image & Voice Processing",
    page_icon="🎥",
    layout="wide"
)

st.title("🎥 Image & Voice Processing WebApp")
st.markdown("Generate image variations and voice signatures using AI")

# Sidebar for configuration
st.sidebar.header("Configuration")
num_variations = st.sidebar.slider("Number of Image Variations", 1, 10, 5)
voice_text = st.sidebar.text_area("Text for Voice Signature", "Hello, this is a voice signature")

# Main content
col1, col2 = st.columns(2)

with col1:
    st.header("📸 Image Processing")
    
    uploaded_image = st.file_uploader(
        "Upload an image", 
        type=['png', 'jpg', 'jpeg'],
        key="image_uploader"
    )
    
    if uploaded_image:
        # Display uploaded image
        image = Image.open(uploaded_image)
        st.image(image, caption="Uploaded Image", use_column_width=True)
        
        # Upload to backend
        if st.button("Generate Image Variations", key="generate_variations"):
            with st.spinner("Uploading and processing image..."):
                try:
                    # Upload image
                    uploaded_image.seek(0) # Reset file pointer to the beginning
                    files = {"file": uploaded_image}
                    upload_response = requests.post(f"{BACKEND_URL}/upload-image", files=files)
                    
                    if upload_response.status_code == 200:
                        filename = upload_response.json()["filename"]
                        st.success(f"Image uploaded: {filename}")
                        
                        # Generate variations
                        variation_response = requests.post(
                            f"{BACKEND_URL}/generate-image-variations-gemini",
                            params={"filename": filename, "num_variations": num_variations}
                        )
                        
                        if variation_response.status_code == 200:
                            variations = variation_response.json()["variations"]
                            st.success("Image variations generated successfully!")
                            
                            # Display variations
                            st.subheader("Generated Variations")
                            if isinstance(variations, dict) and "images" in variations:
                                if variations["images"]:
                                    for i, variation in enumerate(variations["images"]):
                                        st.write(f"Variation {i+1}: {variation.get('filename', 'Unknown file')}")
                                        # Assuming 'path' is available and accessible from the frontend
                                        # For now, just display filename or a placeholder
                                else:
                                    st.info("No image variations were generated by the AI model.")
                            else:
                                st.error("Unexpected response format for image variations.")
                                
                        else:
                            st.error(f"Failed to generate variations: {variation_response.text}")
                    else:
                        st.error(f"Failed to upload image: {upload_response.text}")
                        
                except Exception as e:
                    st.error(f"Error: {str(e)}")

with col2:
    st.header("🎤 Voice Processing")
    
    uploaded_voice = st.file_uploader(
        "Upload a voice file", 
        type=['mp3', 'wav', 'ogg', 'm4a'],
        key="voice_uploader"
    )
    
    if uploaded_voice:
        # Display audio player
        st.audio(uploaded_voice, format=uploaded_voice.type)
        
        # Upload to backend
        if st.button("Generate Voice Signature", key="generate_signature"):
            with st.spinner("Uploading and processing voice..."):
                try:
                    # Upload voice file
                    uploaded_voice.seek(0) # Reset file pointer to the beginning
                    # Store content type before it might be lost
                    voice_content_type = uploaded_voice.type
                    print(f"Frontend: uploaded_voice.type before sending: {voice_content_type}")
                    uploaded_voice.seek(0) # Reset file pointer to the beginning
                    files = {"file": (uploaded_voice.name, uploaded_voice, voice_content_type)}
                    upload_response = requests.post(f"{BACKEND_URL}/upload-voice", files=files)
                    
                    if upload_response.status_code == 200:
                        filename = upload_response.json()["filename"]
                        st.success(f"Voice file uploaded: {filename}")
                        
                        # Generate voice signature
                        signature_response = requests.post(
                            f"{BACKEND_URL}/generate-voice-signature",
                            params={"filename": filename, "text": voice_text}
                        )
                        
                        if signature_response.status_code == 200:
                            result = signature_response.json()
                            st.success("Voice signature generated successfully!")
                            
                            st.subheader("Voice Signature Details")
                            st.write(f"Voice ID: {result['voice_id']}")
                            
                        else:
                            st.error(f"Failed to generate voice signature: {signature_response.text}")
                    else:
                        st.error(f"Failed to upload voice file: {upload_response.text}")
                        
                except Exception as e:
                    st.error(f"Error: {str(e)}")

# Status section
st.header("🔧 System Status")

col1, col2, col3 = st.columns(3)

with col1:
    if st.button("Check Backend Health"):
        try:
            response = requests.get(f"{BACKEND_URL}/health")
            if response.status_code == 200:
                st.success("✅ Backend is healthy")
            else:
                st.error("❌ Backend is not responding")
        except Exception as e:
            st.error(f"❌ Cannot connect to backend: {str(e)}")

with col2:
    st.metric("Backend URL", BACKEND_URL)

with col3:
    st.metric("Max Variations", num_variations)

# Footer
st.markdown("---")
st.markdown("Built with FastAPI + Streamlit • Deployed on Google Cloud Platform")