runtime: python39

env_variables:
  ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY}
  NANOBANANA_API_KEY: ${NANOBANANA_API_KEY}
  NANOBANANA_API_URL: ${NANOBANANA_API_URL}
  GOOGLE_CLOUD_PROJECT_ID: ${GOOGLE_CLOUD_PROJECT_ID}

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10