version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - NANOBANANA_API_KEY=${NANOBANANA_API_KEY}
      - NANOBANANA_API_URL=${NANOBANANA_API_URL}
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
  
  # Streamlit frontend
  frontend-streamlit:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
  
  # React frontend
  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  uploads:
  outputs: